export const cityList = [
  { name: '全部城市', id: 0 },
  { name: '上海', id: 1 },
  { name: '北京', id: 2 },
  { name: '合肥', id: 3 },
  { name: '南京', id: 4 },
  { name: '苏州', id: 5 },
  { name: '武汉', id: 6 },
  { name: '无锡', id: 7 },
  { name: '常州', id: 8 },
  { name: '杭州', id: 9 },
  { name: '广州', id: 10 },
  { name: '深圳', id: 11 },
  { name: '重庆', id: 12 },
  { name: '长沙', id: 13 },
  { name: '成都', id: 14 },
  { name: '天津', id: 15 },
  { name: '厦门', id: 16 },
  { name: '福州', id: 17 },
  { name: '大连', id: 18 },
  { name: '青岛', id: 19 },
  { name: '哈尔滨', id: 20 },
  { name: '济南', id: 21 },
  { name: '郑州', id: 22 },
  { name: '西安', id: 23 },
  { name: '宁波', id: 24 },
  { name: '石家庄', id: 25 },
]
export const ruleType = [{ type: '物流', id: 1 }, { type: '到家', id: 2 }]

export const data = {
  wuliu: [
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 1111,
      cityName: '宁波',
      taskName: '近日接单培训，引导培训',
      source: '人工设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
  ],
  daojia: [
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
    {
      id: 2222,
      cityName: '上海',
      taskName: '近日接单培训，引导培训',
      source: '系统设置',
      type: '城市任务',
      taskObject: '骑士任务',
      result: '未完成',
      date: '09/25-10/02',
      num: 52,
    },
  ],
}
